services:
  farm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./database:/var/destructivefarm/
      - ./server/config.py:/app/server/config.py
      - ./server/protocols:/app/server/protocols
    ports:
      - 5000:5000

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: huey_worker
    # Запускаем Huey worker для обработки фоновых задач
    entrypoint: huey_consumer.py server.standalone.huey -w 4
    volumes:
      - ./database:/var/destructivefarm/