services:
  farm:
    image: ghcr.io/bekosa/destructivefarm:master
    volumes:
      - ./database:/var/destructivefarm/
      - ./server/config.py:/app/server/config.py
      - ./server/protocols:/app/server/protocols
    ports:
      - 5000:5000