name: Build and Push Container Image

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
  release:
    types:
      - released

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Podman Build and Push Action
        uses: Frozen-Tapestry/container-action@v1
        with:
          login_registry: ghcr.io
          login_username: ${{ secrets.REGISTRY_USERNAME }}
          login_password: ${{ secrets.REGISTRY_PASSWORD }}
          tags: ghcr.io/bekosa/destructive-farm:latest
          dockerfile: Dockerfile
          # Use those security flags if using GitHub Action. Keep the defaults, if using Gitea.
          security: |
            --security-opt=seccomp=unconfined
            --security-opt=apparmor=unconfined
          push: true