name: Build and Push Docker Image in Repository

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: destructive-farm
  REPO_LOWER: "${{ format('{0}/{1}', github.repository_owner, github.event.repository.name) }}"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME}}:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}